### ISSUE TITLE
api.football-data.org IDs (where to find competitions?)

### ISSUE THREAD

**Issue by aminvakil** [dev-labs-bg/sportify#23]
I want to implement your code for FIFA World Cup 2018 which starts in 10 days!

Do you know any new api which works except football-data which doesn't work anymore and doesn't have world cup?

**Comment by cmihaylov** [comment]
Actually it's working. The ID of the world cup is 467, it's just that it's not showed in the list along with the rest of the competitions: http://api.football-data.org/v1/competitions. However, check this URL: http://api.football-data.org/v1/competitions/467 and you have it.

**Comment by aminvakil** [comment]
I will check that asap, thanks.

**Comment by aminvakil** [comment]
How can I find UCL 2018/2019 ID?

**Comment by aminvakil** [comment]
Actually It doesn't support UCL 18/19 on api v1, therefore I should use api v2 and the ID is 2001 if anyone needs to know. Also all competitions can be find in api.football-data.org/v2/competitions.
