### ISSUE TITLE
Matches ending in penalties

### ISSUE THREAD

**Issue by aminvakil** [dev-labs-bg/sportify#29]
Which score will be result of the match when matches end in 120 minutes or end in penalties?
Will the final score be the goals scored by teams in 90 minutes or in 120 minutes or something else?

**Comment by davidus05** [comment]
It depends on you: Which is the fairer method?

**Comment by aminvakil** [comment]
Match result at the end of 120 minutes.If it goes to penalty shooutous then the game must be draw.On Jun 30, 2018 4:03 PM, davidus05 <notifications@github.com> wrote:It depens on you: Which is the fairer method?

**Comment by davidus05** [comment]
I think so, too. But can you currently update the match results? I get an error 500 every time and my cron does not work ...

**Comment by aminvakil** [comment]
```
in src/Devlabs/SportifyBundle/Services/DataUpdates/Importer.php at line 110  -

                    $homeTeamId = $this->em->getRepository('DevlabsSportifyBundle:ApiMapping')
                        ->getByEntityTypeAndApiObjectId('Team', $footballApi, $apiHomeTeamId)
                        ->getEntityId();
                    $awayTeamId = $this->em->getRepository('DevlabsSportifyBundle:ApiMapping')
                        ->getByEntityTypeAndApiObjectId('Team', $footballApi, $apiAwayTeamId)
                        ->getEntityId();


```
I get error 500 too and it's because of this line, although it adds matches but it gives me this error.
-------------------
Edit: It doesn't adds matches anymore.

**Comment by cmihaylov** [comment]
Here's what the API returns for a match with extra time and penaties:
```
"result": {
                "goalsHomeTeam": 1,
                "goalsAwayTeam": 1,
                "halfTime": {
                    "goalsHomeTeam": 1,
                    "goalsAwayTeam": 1
                },
                "extraTime": {
                    "goalsHomeTeam": 1,
                    "goalsAwayTeam": 1
                },
                "penaltyShootout": {
                    "goalsHomeTeam": 3,
                    "goalsAwayTeam": 2
                }
            }
```

Our logic is that we are getting the first two, which is the 90-minute result.
This happens in here:
https://github.com/dev-labs-bg/sportify/blob/master/src/Devlabs/SportifyBundle/Services/DataUpdates/Parsers/FootballDataOrg.php#L51
If you want, you can modify the logic and get the extraTime result.

In my opinion, the 90-min result is correct one to predict. At least that's what all the bookies (that I know) do.

**Comment by davidus05** [comment]
Thanks for the reply, but it would be great that if it would fetch the data at all ...
https://github.com/dev-labs-bg/sportify/issues/31

**Comment by cmihaylov** [comment]
@davidus05 yeah but as I've said in the mentioned issue, in order to identify the problem I need more info on the error/exception that's returned.
